;; This logfile was generated automatically by `xindy'
;; at 04.10.2018  20:26:45
;; Indexstyle: "C:\\Users\\Dani\\Documents\\Bachelorarbeit\\8EpwA6qyJK", Rawindex: "C:\\Users\\Dani\\Documents\\Bachelorarbeit\\RK2cqwqeZh", Output: "iswstud.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "È—" -> "P"
Letter-group: "œ—»" -> "F"
Letter-group: "Ë®¤Ð" -> "R"
Letter-group: "È" -> "P"
Letter-group: "ÐÈ" -> "S"
Letter-group: "´Ð" -> "L"
Letter-group: "Ã„€" -> "O"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "œ—»" -> "F"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´Ð" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ã„€" -> "O"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "È" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ë®¤Ð" -> "R"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÐÈ" -> "S"
Reading raw-index "C:\\Users\\Dani\\Documents\\Bachelorarbeit\\RK2cqwqeZh"...WARNING: location-reference "{}{v}" did match multiple location-classes! (taking first one)
