;; This logfile was generated automatically by `xindy'
;; at 05.08.2018  21:15:23
;; Indexstyle: "C:\\Users\\Dani\\Documents\\Bachelorarbeit\\TQMHmEg0JK", Rawindex: "C:\\Users\\Dani\\Documents\\Bachelorarbeit\\9W5amHE1FN", Output: "iswstud.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "È—" -> "P"
Letter-group: "È" -> "P"
Letter-group: "ÐÈ" -> "S"
Letter-group: "Ë®¤Ë" -> "R"
Letter-group: "´Ð" -> "L"
Letter-group: "Ã„€" -> "O"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´Ð" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ã„€" -> "O"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "È" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ë®¤Ë" -> "R"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÐÈ" -> "S"