;; This logfile was generated automatically by `xindy'
;; at 06.09.2018  16:59:54
;; Indexstyle: "C:\\Users\\Dani\\Documents\\Bachelorarbeit\\bnKK9wYgxw", Rawindex: "C:\\Users\\Dani\\Documents\\Bachelorarbeit\\VM9JLQrJzC", Output: "iswstud.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "È—" -> "P"
Letter-group: "È" -> "P"
Letter-group: "ÐÈ" -> "S"
Letter-group: "Ë®¤Ð" -> "R"
Letter-group: "´Ð" -> "L"
Letter-group: "Ã„€" -> "O"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´Ð" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ã„€" -> "O"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "È" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ë®¤Ð" -> "R"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÐÈ" -> "S"